name: ${APP_NAME:-Laravertex}

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
      - "5173:5173"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/var/www/html
    environment:
      APP_NAME: ${APP_NAME:-laravertex}
      APP_URL: ${APP_URL:-http://localhost:8000}
      VITE_DEV_SERVER_URL: ${VITE_DEV_SERVER_URL:-http://localhost:5173}
      DB_CONNECTION: ${DB_CONNECTION:-pgsql}
      DB_URL: ${DB_URL:-pgsql://root:root@host.docker.internal:5432/laravertex_db}
      DB_HOST: ${DB_HOST:-host.docker.internal}
      DB_PORT: ${DB_PORT:-5432}
      DB_DATABASE: ${DB_DATABASE:-laravertex_db}
      DB_USERNAME: ${DB_USERNAME:-root}
      DB_PASSWORD: ${DB_PASSWORD:-root}
      # Redis
      REDIS_HOST: ${REDIS_HOST:-host.docker.internal}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-null}
      REDIS_PORT: ${REDIS_PORT:-6379}
      CACHE_DRIVER: ${CACHE_DRIVER:-redis}
      CACHE_PREFIX: ${CACHE_PREFIX:-laravertex-cache}
      SESSION_DRIVER: ${SESSION_DRIVER:-redis}
      SESSION_CONNECTION: ${SESSION_CONNECTION:-default}
      SESSION_LIFETIME: ${SESSION_LIFETIME:-120}
      QUEUE_CONNECTION: ${QUEUE_CONNECTION:-redis}
      # MAILER
      MAIL_MAILER: ${MAIL_MAILER:-smtp}
      MAIL_HOST: ${MAIL_HOST:-host.docker.internal}
      MAIL_PORT: ${MAIL_PORT:-1025}
      MAIL_USERNAME: ${MAIL_USERNAME:-null}
      MAIL_PASSWORD: ${MAIL_PASSWORD:-null}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION:-null}
    command: bash -c "php artisan serve --host=0.0.0.0 --port=8000 & npm run dev -- --host"

  worker:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      APP_NAME: ${APP_NAME:-laravertex}
      APP_URL: ${APP_URL:-http://localhost:8000}
      DB_CONNECTION: ${DB_CONNECTION:-pgsql}
      DB_HOST: ${DB_HOST:-host.docker.internal}
      DB_PORT: ${DB_PORT:-5432}
      DB_DATABASE: ${DB_DATABASE:-laravertex_db}
      DB_USERNAME: ${DB_USERNAME:-root}
      DB_PASSWORD: ${DB_PASSWORD:-root}
      REDIS_HOST: ${REDIS_HOST:-host.docker.internal}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-null}
      REDIS_PORT: ${REDIS_PORT:-6379}
      QUEUE_CONNECTION: ${QUEUE_CONNECTION:-redis}
      MAIL_MAILER: ${MAIL_MAILER:-smtp}
      MAIL_HOST: ${MAIL_HOST:-host.docker.internal}
      MAIL_PORT: ${MAIL_PORT:-1025}
    command: php artisan horizon
    depends_on:
      - app

  scheduler:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      APP_NAME: ${APP_NAME:-laravertex}
      APP_URL: ${APP_URL:-http://localhost:8000}
      DB_CONNECTION: ${DB_CONNECTION:-pgsql}
      DB_HOST: ${DB_HOST:-host.docker.internal}
      DB_PORT: ${DB_PORT:-5432}
      DB_DATABASE: ${DB_DATABASE:-laravertex_db}
      DB_USERNAME: ${DB_USERNAME:-root}
      DB_PASSWORD: ${DB_PASSWORD:-root}
      REDIS_HOST: ${REDIS_HOST:-host.docker.internal}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-null}
      REDIS_PORT: ${REDIS_PORT:-6379}
      QUEUE_CONNECTION: ${QUEUE_CONNECTION:-redis}
      MAIL_MAILER: ${MAIL_MAILER:-smtp}
      MAIL_HOST: ${MAIL_HOST:-host.docker.internal}
      MAIL_PORT: ${MAIL_PORT:-1025}
    command: php artisan schedule:work
    depends_on:
      - app
